multiapps/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tickets.urls', namespace='booking')),
    path('registration/', include('registration.urls', namespace='registration')),  # пространство имен registration
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registration/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from .views import register_view


app_name = 'registration'

urlpatterns = [

path('register/', register_view, name='register'),
path('login/', LoginView.as_view(template_name='login.html'), name='login'),
path('logout/', LogoutView.as_view(next_page='/'), name='logout'),

]

tickets/urls.py
from django.urls import path
from .views import SessionListView, BookSeatsView, SuccessfulBookingView


app_name = 'booking'

urlpatterns = [
    path('', SessionListView, name='session_list'),      # Список всех сеансов
    path('book/<int:pk>/', BookSeatsView.as_view(), name='book_seats'),  # Бронирование мест
    path('successful_booking/', SuccessfulBookingView, name='successful_booking'),
]

tickets/models.py
from django.db import models
from django.conf import settings
from django.core.validators import FileExtensionValidator


# Кинотеатр
class Cinema(models.Model):
    name = models.CharField(max_length=100)  # Название кинотеатра
    address = models.TextField()  # Адрес кинотеатра
    image = models.ImageField(upload_to='cinemas/', blank=True, null=True, validators=[FileExtensionValidator(['jpg', 'png', 'jpeg'])])

    def __str__(self):
        return self.name


# Сеанс фильма
class Session(models.Model):
    cinema = models.ForeignKey(Cinema, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)  # Название фильма
    description = models.TextField(blank=True, null=True)  # Описание фильма (необязательно)
    poster = models.ImageField(upload_to='movies/', blank=True, null=True, validators=[FileExtensionValidator(['jpg', 'png', 'jpeg'])])  # Постер фильма
    date_time = models.DateTimeField()  # Дата и время показа
    total_seats = models.PositiveIntegerField()  # Общее число мест в зале

    def available_seats(self):
        """Возвращает доступное количество мест"""
        booked_tickets_count = self.bookedticket_set.count()
        return max(0, self.total_seats - booked_tickets_count)

    def __str__(self):
        return f"{self.title} ({self.date_time.strftime('%Y-%m-%d %H:%M')})"

    class Meta:
        ordering = ["date_time"]  # сортировка по дате


# Бронирование билета
class BookedTicket(models.Model):
    session = models.ForeignKey(Session, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    seat_number = models.PositiveIntegerField()

    def __str__(self):
        return f"Билет на '{self.session.title}', кресло №{self.seat_number}"

    class Meta:
        unique_together = ("session", "seat_number")

tickets/forms.py
from django import forms

class BookingForm(forms.Form):
    selected_seats = forms.MultipleChoiceField(label="Выберите места", widget=forms.CheckboxSelectMultiple)

    def clean_selected_seats(self):
        seats = self.cleaned_data['selected_seats']
        # Любые дополнительные проверки
        return seats

class BookingForm(forms.Form):
   selected_seats = forms.MultipleChoiceField(label="Выберите места:", widget=forms.CheckboxSelectMultiple)

   def __init__(self, *args, **kwargs):
       free_seats = kwargs.pop('free_seats', [])
       super().__init__(*args, **kwargs)
       self.fields['selected_seats'].choices = [(s, s) for s in free_seats]

tickets/views.py
from django.template.defaultfilters import title
from django.utils.decorators import method_decorator
from django.views.generic import ListView, FormView, TemplateView
from django.shortcuts import render, redirect, get_object_or_404
from .forms import BookingForm
from .models import Session, Cinema, BookedTicket
from .booking_manager import BookingManager
from django.contrib.auth.decorators import login_required

# class SessionListView(ListView):
#     model = Session
#     template_name = 'sessions.html'
#
#     context_object_name = 'sessions'


def SessionListView(request):
    title: str = "Доступные сеансы"
    sessions = Session.objects.all()
    cinema = Cinema.objects.all()
    return render(request, 'sessions.html', {
        'title': title,
        'sessions': sessions,
        'cinema': cinema
    })



# class SuccessfulBookingView(TemplateView):
#     template_name = 'successful_booking.html'


def SuccessfulBookingView(request):
    title: str = "Информация о брони"
    sessions = Session.objects.all()
    cinema = Cinema.objects.all()
    booked_tickets = BookedTicket.objects.filter(user=request.user)
    return render(request, 'successful_booking.html', {
        'title': title,
        'sessions': sessions,
        'cinema': cinema,
        'tickets': booked_tickets
    })

@method_decorator(login_required(login_url='/registration/login/'), name='dispatch')
class BookSeatsView(FormView):
    form_class = BookingForm
    template_name = 'book_seats.html'
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        session_id = self.kwargs.get('pk')
        session = get_object_or_404(Session, pk=session_id)
        context['session'] = session

        # Генерация списка свободных мест
        taken_seats = set(session.bookedticket_set.values_list('seat_number', flat=True))
        all_seats = range(1, session.total_seats + 1)
        free_seats = sorted(set(all_seats) - taken_seats)
        context['free_seats'] = free_seats

        return context

    def post(self, request, *args, **kwargs):
        session_id = kwargs.get('pk')
        form = self.form_class(data=request.POST, free_seats=self.get_context_data()['free_seats'])

        if form.is_valid():
            seat_numbers = form.cleaned_data['selected_seats']
            user = request.user

            print(f"Selected Seats: {seat_numbers}, User: {user.username}, Session ID: {session_id}")

            manager = BookingManager()
            if manager.reserve_seats(session_id, seat_numbers, user):
                return redirect('booking:successful_booking')
            else:
                error_message = f"Недостаточно свободных мест."
                return render(request, self.template_name, {'form': form, 'error_message': error_message})
        else:
            print(form.errors.as_json())
            return super().post(request, *args, **kwargs)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <style>
        body {font-family: Arial, sans-serif;}
        h1 {text-align: center; text-transform: uppercase;}
        input[type="number"] {width: 150px; text-align: center; color: green;}
        button {padding: 10px 20px; background-color: #4CAF50; color: white; border: none; cursor: pointer; border-radius: 5px; margin-top: 20px; text-transform: uppercase;}
        p.error {color: red; font-size: 1.2em; text-align: center;}
    </style>
</head>
<body >

    <header style=" border: 1px solid green; border-radius: 10px; max-width: 70%; text-align: center; margin: 0 auto 20px; margin-bottom: 30px; background: green;
    color: white; display: flex; flex-wrap: wrap; align-items: stretch; justify-content: space-between;  padding-right: 10px; padding-left: 10px;">
           <div><h1><a  style="padding: 5px 5px; background-color: #4CAF50; color: white; border: none; cursor: pointer;
                          border-radius: 5px; text-decoration: none; text-transform: uppercase;" href="{% url 'booking:session_list' %}">БИЛЕТЫ В КИНО</a></h1></div>
            <div>
                {% if user.is_authenticated %}
                    <div style="padding-top: 50px 0 0 0 ; ">Вы зарегистрированы как: <b>{{ user.username }}</b></div>
                    <div style="padding-bottom: 10px;">
                        <form method="post" action="{% url 'registration:logout' %}">
                            {% csrf_token %}
                            <button  type="submit">Выйти</button>
                        </form>
                    </div>
                {% else %}
                <div style="display: flex; padding-top: 10px; padding: 30px 0 10px 0;">
                    <div><a style="padding: 10px 20px; background-color: #4CAF50; color: white; border: none; cursor: pointer;
                          border-radius: 5px; text-decoration: none; text-transform: uppercase; margin-right: 20px;" href="{% url 'registration:login' %}">Войти</a></div>
                    <div><a  style="padding: 10px 20px; background-color: #4CAF50; color: white; border: none; cursor: pointer;
                          border-radius: 5px; text-decoration: none; text-transform: uppercase;" href="{% url 'registration:register' %}">Регистрация</a></div>
                </div>
                {% endif %}
            </div>
    </header>

    <div>
        <main>
                {% block content %}
                <!-- Здесь дочерние шаблоны вставят свой HTML -->
                {% endblock %}
        </main>

        <footer style="border: 1px solid green; border-radius: 10px; max-width: 70%; padding: 10px 10px 20px; text-align: center; margin: 0 auto 20px; margin-bottom: 80px; background: green; color: white;">
            <div>
                <div>
                    <p>© 2025 Учебный проект Django Tickets:</p>
                    <p>Alpono24</p>
                    <p>alex.ponovarov@mail.ru</p>
                </div>
            </div>
        </footer>
    </div>
</body>

</html>

tickets/templates/book_seats.html
{% extends "base.html" %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Бронирование мест</title>
    <style>
        body {font-family: Arial, sans-serif;}
        h1, h2, h3 {text-align: center; text-transform: uppercase;}
        ul {
            list-style-type: none;
            display: flex;
            justify-content: center;
            gap: 10px;
            flex-wrap: wrap;
        }
        li {
            background-color: lightgreen;
            padding: 10px;
            border-radius: 5px;
        }
        button[type="submit"] {
            margin-top: 20px;
            padding: 10px 20px;
            background-color: #4CAF50;
            color: white;
            border: none;
            cursor: pointer;
            border-radius: 5px;
        }
    </style>
</head>

<div style="max-width: 70%; margin: 0 auto; padding: 20px; border: 1px solid lightgray; border-radius: 10px;">
    <h1>Выбор мест:</h1>

    <!-- Форма для бронирования -->
    <form method="POST" action="{% url 'booking:book_seats' pk=session.pk %}">
        {% csrf_token %}

        <!-- Список доступных мест -->
        {% if free_seats %}
            <ul>
                {% for seat in free_seats %}
                    <li>
                        <label>
                            <input type="checkbox" name="selected_seats" value="{{ seat }}"/>
                            Место №{{ seat }}
                        </label>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p style="color: red; font-weight: bold; text-align: center;">Все места заняты!</p>
        {% endif %}

        <button type="submit">Забронировать</button>
    </form>

    <!-- Вывод сообщений об ошибках -->
    {% if error_message %}
        <p style="color: red; font-weight: bold; text-align: center; margin-top: 20px;">{{ error_message }}</p>
    {% endif %}
</div>
{% endblock %}

tickets/templates/info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

Задание 2
Многопоточная система бронирования билетов в ĸинотеатр
Цель:
Разработать многопоточное приложение на Python, ĸоторое моделирует
систему бронирования билетов для ĸинотеатра, обрабатывающую запросы в
реальном времени и поддерживающую одновременное бронирование на
разные сеансы.
Описание задачи:
Система должна позволять пользователям выбирать фильм и сеанс, после чего
они могут бронировать одно или несĸольĸо мест. При этом должна
поддерживаться синхронизация доступа ĸ данным о доступных местах, чтобы
предотвратить двойное бронирование одного и того же места.

Техничесĸие требования:
• Использовать threading модуль для многопоточности.
• Применить мьютеĸсы (threading.Lock), семафоры (threading.Semaphore)
и условные переменные (threading.Condition) для управления доступом
и синхронизации потоĸов.
• Обеспечить ĸорреĸтное управление состояниями гонĸи и избежать
дедлоĸов.
Подзадачи:
1. Моделирование данных кинотеатра:
o Создать класс Cinema, который хранит информацию о различных
фильмах и доступных сеансах.
o Каждый сеанс должен иметь информацию о доступных местах.
2. Функция бронирования мест:
o Реализовать методы для выбора фильма, сеанса и бронирования
мест.
o Использовать условные переменные для уведомления о событиях
изменения состояния мест (например, освобождение места).
3. Многопоточная обработка запросов на бронирование:
o Создать потоки для обработки входящих запросов на
бронирование мест.
o Использовать семафоры для ограничения количества
одновременных операций бронирования.
4. Синхронизация доступа к данным:
o Использовать мьютексы для защиты доступа к данным о сеансах и
местах.
o Обеспечить, чтобы бронирование мест было атомарно.

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('MYSQL_DB_NAME'),
        'USER': os.environ.get('MYSQL_DB_USER'),
        'PASSWORD': os.environ.get('MYSQL_DB_PASSWORD'),
        'HOST': os.environ.get('MYSQL_DB_HOST', 'localhost'),
        'PORT': os.environ.get('MYSQL_DB_PORT', '3306'),
    }
}

</body>
</html>

tickets/templates/sessions.html
{% extends "base.html" %}

{% block content %}

<head>
    <meta charset="UTF-8">
    <title>Список сеансов</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }
        h1, h2, h3 {
            text-align: center;
            text-transform: uppercase;
        }
    </style>
</head>

<body>
    <h1 style="text-align: center; text-transform: uppercase;">{{title}}</h1>
    {% for session in sessions %}
        <div style="border: 1px solid green; border-radius: 10px; max-width: 70%; padding: 10px 10px 20px; text-align: center; margin: 0 auto 20px;">

             <div style="display: flex; justify-content: center; align-items: stretch; gap: 20px; flex-wrap: wrap; ">
                 <div>
                    <h3 style="color: blue;"><strong>Кинотеатр:</strong> {{ session.cinema.name }}</h3>

                    {% if session.cinema.image %}
                        <div><img style="max-width: 250px;" src="{{ session.cinema.image.url }}" alt="Cinema Image"></div>
                    {% else %}
                        <p>Изображение кинотеатра отсутствует.</p>
                    {% endif %}
                 </div>
                 <div>
                    <h3 style="color: green;"><strong>Фильм:</strong> {{ session.title }}</h3>

                    {% if session.poster %}
                        <div><img style="max-width: 200px;" src="{{ session.poster.url }}" alt="Poster Image"></div>
                    {% else %}
                        <p>Изображение кинотеатра отсутствует.</p>
                    {% endif %}
                 </div>
            </div>
            <p style="color: orange;"><strong>Время сеанса:</strong> {{ session.date_time|date:"d.m.Y H:i" }}</p>

            <!-- Здесь используем новый метод available_seats -->
            <p><strong>Свободных мест:</strong> {{ session.available_seats }}</p>
            <p><strong>Всего мест:</strong> {{ session.total_seats }}</p>

            <!-- Проверка доступна ли бронь -->
            {% if session.available_seats > 0 %}
                <a style="padding: 10px 20px; background-color: #4CAF50; color: white; border: none; cursor: pointer;
                         border-radius: 5px; text-decoration: none; text-transform: uppercase;"
                   href="{% url 'booking:book_seats' pk=session.id %}">Забронировать билеты</a>
            {% else %}
                <span style="border: 1px solid red; padding: 10px 75px; text-align: center; border-radius: 5px; color: red; font-weight: bold;">Нет билетов</span>
            {% endif %}
        </div>
    {% empty %}
        <div style="border: 1px solid green; padding: 10px 10px; text-align: center;">Нет доступных сеансов.</div>
    {% endfor %}
</body>

{% endblock %}

tickets/templates/successful_booking.html
{% extends "base.html" %}

{% block content %}

    <head>
        <meta charset="UTF-8">
        <title>Информация!</title>
        <style>
            label {display: inline-block; width: 150px; font-weight: bold;}
        </style>
    </head>
    <body>
        <div style="border: 1px solid green; border-radius: 10px; max-width: 70%; padding: 10px 10px; text-align: center; margin: 0 auto 20px;">
                <h1>Информируем </h1>
            <p>Уважаемый пользователь {{ user.username }}! </br>
               Поздравляем Вас!</br>
               Вы успешно забронировали билеты!</p>

             {% if tickets %}
            <h2>Ваши билеты:</h2>

                {% for ticket in tickets %}
                    <p>{{ ticket }}</p>
                {% endfor %}

            {% else %}
                <p>Вы ещё не купили ни одного билета.</p>
            {% endif %}


        </div>
    </body>

{% endblock %}